version: '3.7'
services:
    jenkins:
        image: jenkinsci/blueocean:latest
        container_name: jenkins
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - ./jenkins-data:/var/jenkins_home
        ports:
            - "8080:8080"
        expose:
            - "8080"
            - "50000"
        privileged: true
        user: root
        restart: always